language: node_js
node_js:
  node
branches:
  only:
    - master
before_script: npm install instanbul -g
after_script: NODE_ENV=test instanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage